apiVersion: v1
kind: Service
metadata:
  name: mywebapi-service
spec:
  selector:
    app: mywebapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # For external access
